---
  - name: "Thinkpad configurations and installation"
    hosts: localhost
    connection: local 
    become: true

    vars_files:
      - /mnt/ansible/vars.vault.yml

    roles:
      - configs
      # - apps
      # - docker
