---
  - name: "Thinkpad configurations and installation"
    hosts: localhost
    connection: local 
    become: true

    vars_files:
      - /mnt/ansible/vars.vault.yml

    roles:
      - apps
      - configs
      - docker
    
    tasks:
      - name: Show message
        debug:
          msg: "The host will reboot in 10 seconds."
      
      - name: Schedule reboot after 10 seconds
        command: "sleep 10 && sudo reboot"
        async: 0
        poll: 0
