---
# ------------------------------
# Tasks for configuraing .bashrc
# ------------------------------
- name: Check if .bashrc exists
  stat:
    path: "{{ default_user_home }}/.bashrc"
  register: bashrc_stat

- name: Back up .bashrc if exists
  when: bashrc_stat.stat.exists
  ansible.builtin.command: mv {{ default_user_home }}/.bashrc {{ default_user_home }}/.bashrc.ansible.{{ ansible_date_time.iso8601 }}
  changed_when: false

- name: Remove default .bashrc
  when: bashrc_stat.stat.exists
  ansible.builtin.file:
    state: absent
    path: "{{ default_user_home }}/.bashrc"

- name: Create custom .bashrc file
  file:
    path: "{{ default_user_home }}/.bashrc"
    state: touch

- name: Read custom .bashrc file
  ansible.builtin.slurp:
    src: "{{ role_path }}/files/bashrc"
  register: bashrc_file_content

- name: Append to custom .bashrc file
  ansible.builtin.lineinfile:
    path: "{{ default_user_home }}/.bashrc"
    line: "{{ bashrc_file_content['content'] | b64decode | regex_replace('\n', '\\n') }}"
    insertafter: EOF
    state: present
  