---
- name: Creating Docker Group
  ansible.builtin.group:
    name: docker
    state: present

- name: Adding default user to docker group {{ default_user }}
  ansible.builtin.user:
    name: "{{ default_user }}"
    groups: "docker"
    append: true

- name: Copying custom daemon.json file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/daemon.json"
    dest: /etc/docker
    owner: root
    group: root
    mode: "0644"
    force: true

- name: Ensuring docker service is running
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
