---
- name: Ensure default home directories exist
  ansible.builtin.file:
    path: "{{ default_user_home }}/{{ item }}"
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: "0755"
  loop:
    - .themes
    - .icons
    - repos

- name: Mount NFS volumes
  include_tasks: nfs.yml

- name: Add ssh keys
  include_tasks: ssh.yml

- name: Add vars to bashrc
  include_tasks: bashrcvars.yml
  no_log: true

- name: Check if Oh My Bash is installed
  stat:
    path: "{{ default_user_home }}/.oh-my-bash"
  register: directory_check

- name: Configure Oh My Bash if installed
  include_tasks: ohmybash.yml
  when: directory_check.stat.exists

- name: Configure .vimrc
  include_tasks: vimrc.yml

- name: Configure sublime text
  include_tasks: sublime.yml

- name: Configure Terminator terminal
  include_tasks: terminator.yml
