---
# ---------------
# Install Sublime
# ---------------
- name: Add Sublime Text GPG key
  ansible.builtin.apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present


- name: Add Sublime Text repository
  ansible.builtin.apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present

# -------
# AWS cli
# -------
- name: Download aws cli zip
  ansible.builtin.get_url: 
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip 
    dest: /tmp/awscliv2.zip

- name: Unzip AWS cli archive
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    copy: no

- name: Install AWS cli tool
  shell: /tmp/aws/install --update 

# ------------
# Deb packages
# ------------
- name: Install .deb packaged apps
  include_tasks: deb_packages.yml

# -----------
# Apt and pip
# -----------
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true

- name: Wait for apt lock
  ansible.builtin.shell: while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done;
  changed_when: false

- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: present
    force_apt_get: true

- name: Install pip apps and packages
  include_tasks: pip.yml

# -------
# Scripts
# -------
- name: Check if Oh My Bash is installed
  stat:
    path: "{{ default_user }}/.oh-my-bash"
  register: directory_check

- name: Install Oh My Bash if not already installed
  ansible.builtin.shell: |
    bash -c "$(wget https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh -O -)"
  become_user: "{{ default_user }}"
  when: not directory_check.stat.exists
