---
# ---------------
# Install Sublime
# ---------------
- name: Add Sublime Text GPG key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present


- name: Add Sublime Text repository
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present


- name: Update and Install Sublime Text
  apt:
    name: sublime-text
    state: present
    update_cache: true

# --------------
# Install VSCode
# --------------
- name: Download VSCode Debian package
  get_url:
    url: "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
    dest: "/tmp/code.deb"

- name: Install VSCode from Debian package
  apt:
    deb: "/tmp/code.deb"
    state: present

- name: Remove downloaded Debian package
  file:
    path: "/tmp/code.deb"
    state: absent

# -------
# AWS cli
# -------
- name: Download aws cli zip
  get_url: 
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip 
    dest: /tmp/awscliv2.zip

- name: Unzip AWS cli archive
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    copy: no

- name: Install AWS cli tool
  shell: /tmp/aws/install --update 

- name: Install flatpak apps
  include_tasks: flatpaks.yml

- name: Install .deb packaged apps
  include_tasks: deb_packages.yml
