---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true

- name: Wait for apt lock
  ansible.builtin.shell: while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done;
  changed_when: false

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: true

- name: Install pip apps and packages
  include_tasks: pip.yml

- name: Add the Flathub repository
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  changed_when: false

